[tool.black]
line-length = 120

[tool.pylint.master]
disable = [
    "missing-module-docstring",
    "too-few-public-methods",
    "too-many-arguments"
]
extension-pkg-whitelist = [
    "pygame"
]

[tool.pylint.format]
max-line-length = 120
good-names = ["i", "j", "x", "y"]
